-- ==============================================================================
-- EXHIBITION PLATFORM: RLS PUBLIC POLICIES & REQUESTED STALL ID MIGRATION
-- Execute this script in your Supabase Project -> SQL Editor
-- ==============================================================================

-- 1. Add requested_stall_id column to vendor_requests table (Nullable)
ALTER TABLE IF EXISTS vendor_requests 
ADD COLUMN IF NOT EXISTS requested_stall_id bigint REFERENCES stall_slots(id) ON DELETE SET NULL;

-- Also add reference_id if not present
ALTER TABLE IF EXISTS vendor_requests 
ADD COLUMN IF NOT EXISTS reference_id text;

-- 2. Ensure RLS is enabled and public anon SELECT is allowed on past_event_stories
ALTER TABLE IF EXISTS past_event_stories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read past_event_stories" ON past_event_stories;
CREATE POLICY "Allow public read past_event_stories" 
ON past_event_stories 
FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow anon insert past_event_stories" ON past_event_stories;
CREATE POLICY "Allow anon insert past_event_stories" 
ON past_event_stories 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update past_event_stories" ON past_event_stories;
CREATE POLICY "Allow anon update past_event_stories" 
ON past_event_stories 
FOR UPDATE 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow anon delete past_event_stories" ON past_event_stories;
CREATE POLICY "Allow anon delete past_event_stories" 
ON past_event_stories 
FOR DELETE 
TO anon, authenticated 
USING (true);

-- 3. Ensure RLS allows public anon SELECT on stall_slots
ALTER TABLE IF EXISTS stall_slots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read stall_slots" ON stall_slots;
CREATE POLICY "Allow public read stall_slots" 
ON stall_slots 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- 4. Ensure RLS allows public anon SELECT on exhibitions
ALTER TABLE IF EXISTS exhibitions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read exhibitions" ON exhibitions;
CREATE POLICY "Allow public read exhibitions" 
ON exhibitions 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- 5. Ensure RLS allows public anon INSERT and SELECT on vendor_requests
ALTER TABLE IF EXISTS vendor_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert vendor_requests" ON vendor_requests;
CREATE POLICY "Allow public insert vendor_requests" 
ON vendor_requests 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read vendor_requests" ON vendor_requests;
CREATE POLICY "Allow public read vendor_requests" 
ON vendor_requests 
FOR SELECT 
TO anon, authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow public update vendor_requests" ON vendor_requests;
CREATE POLICY "Allow public update vendor_requests" 
ON vendor_requests 
FOR UPDATE 
TO anon, authenticated 
USING (true);

-- 6. Ensure RLS allows public anon INSERT and SELECT on referrals
CREATE TABLE IF NOT EXISTS referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_name text NOT NULL,
  referrer_phone text NOT NULL,
  referrer_email text,
  referrer_brand text,
  referee_name text NOT NULL,
  referee_phone text NOT NULL,
  referee_brand text NOT NULL,
  referee_category text,
  exhibition_id bigint REFERENCES exhibitions(id) ON DELETE SET NULL,
  incentive_tier text DEFAULT '5% Cash Cashback',
  status text DEFAULT 'pending',
  reference_id text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE IF EXISTS referrals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert referrals" ON referrals;
CREATE POLICY "Allow public insert referrals" 
ON referrals 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read referrals" ON referrals;
CREATE POLICY "Allow public read referrals" 
ON referrals 
FOR SELECT 
TO anon, authenticated 
USING (true);
